# meta: alembic revision template (standard, trimmed).
"""flag verifier

Revision ID: 9260ac3927a3
Revises: 6d48d50cc391
Create Date: 2026-07-24 15:58:09.567743
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9260ac3927a3'
down_revision: Union[str, None] = '6d48d50cc391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('verifier_agrees', sa.Boolean(), nullable=True))
    op.add_column('flags', sa.Column('verifier_model', sa.String(), nullable=True))
    op.add_column('flags', sa.Column('verifier_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flags', 'verifier_reason')
    op.drop_column('flags', 'verifier_model')
    op.drop_column('flags', 'verifier_agrees')
    # ### end Alembic commands ###
